name: Daily Paper Analysis

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:
  pull_request:
    branches:
      - main  # or master, depending on your default branch
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .  # Install the package in editable mode

    - name: Run analyzer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PYTHONPATH: ${{ github.workspace }}/src
      run: python src/analyzer.py